/*
5.1     SQL_terminal_character

Function
Define the terminal symbols of the SQL language and the elements of strings.

**EXHAUSTIVE LIST OF CHARACTERS USED IN SQL**

*/
SQL_terminal_character ::=
  SQL_language_character

SQL_language_character ::=
    simple_Latin_letter
  | digit
  | SQL_special_character

simple_Latin_letter ::=
    simple_Latin_upper_case_letter
  | simple_Latin_lower_case_letter

simple_Latin_upper_case_letter ::=
    "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O"
  | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"

simple_Latin_lower_case_letter ::=
    "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o"
  | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"

digit ::=
    "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

SQL_special_character ::=
      space
  |   double_quote
  |   percent
  |   ampersand
  |   quote
  |   left_paren
  |   right_paren
  |   asterisk
  |   plus_sign
  |   comma
  |   minus_sign
  |   period
  |   solidus
  |   colon
  |   semicolon
  |   less_than_operator
  |   equals_operator
  |   greater_than_operator
  |   question_mark
  |   left_bracket
  |   right_bracket
  |   circumflex
  |   underscore
  |   vertical_bar
  |   left_brace
  |   right_brace
  |   dollar_sign
  |   apostrophe

name_forbidden_characters ::= 
    left_brace
  | right_brace
  | plus_sign
  | minus_sign
  | solidus
  | asterisk
  | quote
  | semicolon
  | equals_operator
  | ampersand
  | vertical_bar
  | hash
  | less_than_operator
  | greater_than_operator
  | circumflex
  | double_quote
  | left_bracket
  | right_bracket
  | left_paren
  | right_paren
  | percent
;

space ::=
  "!! See the Syntax Rules."

double_quote ::=
  '"'

percent ::=
  '%'

ampersand ::=
  '&'

quote ::=
  "'"

left_paren ::=
  '('

right_paren ::=
  ')'

asterisk ::=
  '*'

plus_sign ::=
  '+'

comma ::=
  ','

minus_sign ::=
  '-'

period ::=
  '.'

solidus ::=
  '/'

colon ::=
  ':'

semicolon ::=
  ';'

less_than_operator ::=
  '<'

equals_operator ::=
  '='

greater_than_operator ::=
  '>'

question_mark ::=
  '?'

left_bracket ::=
  '['

right_bracket ::=
  ']'

circumflex ::=
  '^'

underscore ::=
  '_'

vertical_bar ::=
  '|'

left_brace ::=
  '{'

right_brace ::=
  '}'

dollar_sign ::=
  '$'

apostrophe ::=
  "'"

hash ::=
  "#"
;

/*
5.2     token and separator
Function
Specify lexical units (tokens and separators) that participate in SQL language.
Format
*/

create_statement ::=
    "CREATE TABLE" space table_name
  | "CREATE DATABASE" space database_name
  ;

use_statement ::=
    "USE" space database_name
;

drop_statement ::=
    "DROP TABLE" space table_name
  | "DROP DATABASE" space database_name
  ;

table_name ::=
  SQL_language_character excluding name_forbidden_characters
;

root_statment = term_keyword | nonterm_keyword follower_keyword

